sudo: false
language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - gemfiles/capybara_2.gemfile
  - gemfiles/capybara_3.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/latest.gemfile

addons:
  apt:
    packages:
      - mplayer

cache: bundler

